gogs_use_mysql: true
gogs_db_name: gogs
gogs_db_username: (database_server_user)
gogs_db_password: (database_server_password)
gogs_db_host: (database_server_hostname) 
gogs_domain_url: (gogs_server_hostname)
